### ISSUE TITLE
Redact tokens from logs

### ISSUE THREAD

**Issue by simongottschlag** [fluxcd/notification-controller#160]
It would be nice if we could redact tokens from logs.

**Comment by phillebaba** [comment]
Are tokens included in all logs or just ones where they are included in the errors returned by the client?

**Comment by simongottschlag** [comment]
I've seen it with the GitHub client when it errors

**Comment by phillebaba** [comment]
So the error seems to come from net/http, which adds the token to the error message which is then logged. This occurs when the header value is malformed, like adding a trailing new line to the token. This seems to happen a lot as some OS seems to add one by default when base64 encoding a value. Even if this is an error caused by net/http it should be considered a bug here as we should protect end users if they ever add new lines to their base64 encoded secret value.

For more details here is a similar issue in kubernetes.
https://github.com/kubernetes/kubernetes/issues/52919

**Comment by stefanprodan** [comment]
Maybe we should remove the new lines before setting the headers and log an error that the secret values contain invalid data.

**Comment by phillebaba** [comment]
Yep sounds like a good idea, but it would be nice if we could globally filter logs and remove occurrences of a token in case tokens are logged from other errors.
