### ISSUE TITLE
Helm new chart version available notification example

### ISSUE THREAD

**Issue by marianobilli** [fluxcd/notification-controller#266]
I was not able to find an example or documentation on how to set up a notification when a newer chart is available on the helm  repository. 

First I would like to know if it can be done and second how.

Thanks!

**Comment by antoineozenne** [comment]
I'm migrating all my Helm releases to Flux. For now, I use a `CronJob` with <https://github.com/FairwindsOps/nova> that sends an email with the report. But I just realized it won't be possible anymore with Flux because Nova relies on Kubernetes secrets created by Helm (`sh.helm.release.v1.chart.v1`), and Flux does not create Helm secrets.

**Comment by stefanprodan** [comment]
> Flux does not create Helm secrets.

We do create secrets, Flux uses Helm packages so a release made by Flux is no different from one made with Helm CLI.

**Comment by antoineozenne** [comment]
> > Flux does not create Helm secrets.
> 
> We do create secrets, Flux uses Helm packages so a release made by Flux is no different from one made with Helm CLI.

Oups, sorry and thank you for the correction @stefanprodan. You're right, I made a mistake when I tested.
