### ISSUE TITLE
Notifications of errors and recoveries

### ISSUE THREAD

**Issue by sylr** [fluxcd/notification-controller#76]
It would be nice if we could have a setting which would allow to be notified when:

- an error occurs after previous apply was successful.
- an apply is successful after previous one was in error.

This would limit notification traffic to what's really important.

Regards.

**Comment by phillebaba** [comment]
This would require notification-controller to be aware of previous events unless the Kustomization or Helm controller can do this. Either way I do not think it is a good idea for the notification controller to track state of different events. I do however think it would be feasible to implement this in the one of the other controllers so that they send events when a resource recovers.

**Comment by raffis** [comment]
This needs to be fixed somewhere, either having the notification controller stateful or all other controllers only sending events in some circumstances. Also see https://github.com/fluxcd/kustomize-controller/issues/203 where I reported this issue as well.

**Comment by phillebaba** [comment]
I will close this issue as the notification controller has implemented a rate limiter to the event handler.
